# SPDX-FileCopyrightText: 2022 Peter Lemenkov <lemenkov@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

extraction:
  cpp:  
    prepare:
      packages:
        - libgraphicsmagick1-dev
        - libpng-dev
        - libexiv2-dev
        - libtiff-dev
        - libjpeg-dev
        - libxml2-dev
        - libbz2-dev
        - libfreetype6-dev
        - libpstoedit-dev
        - autoconf
        - automake
        - libtool
        - intltool
        - autopoint
    after_prepare:
      - ./autogen.sh
    configure:
      command: ./configure
