# Your .github/workflows/coverity.yml file.
name: Coverity scan

# We only want to test official release code, not every pull request.
on:
  push:
    branches: [master]

jobs:
  coverity:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: prebuilt step
    - run: sudo apt update
    - run: sudo apt install -y libgraphicsmagick1-dev libpng-dev libexiv2-dev libtiff-dev libjpeg-dev libxml2-dev libbz2-dev libfreetype6-dev libpstoedit-dev autoconf automake libtool intltool autopoint
    - run: ./autogen.sh
    - run: ./configure

    - uses: vapier/coverity-scan-action@v1
    - name: actual check
      with:
        email: ${{ secrets.COVERITY_SCAN_EMAIL }}
        token: ${{ secrets.COVERITY_SCAN_TOKEN }}
